name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2.2.1

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: giancarloh
        password: ${{ secrets.DOCKERHUB_PWD }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: giancarloh/go_ci:${{ github.ref_name }}

